name: "拉取文件"

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download location.json
        run: |
          curl -L \
            https://github.com/pyecharts/geo-region-coords/raw/refs/heads/master/coords.json \
            -o coords.json

      - name: Commit file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add coords.json
          git commit -m "Update coords.json" || echo "No changes to commit"
          git push
