name: Download location.json

on:
  workflow_dispatch:   # 只手动触发

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download location.json
        run: |
          curl -L \
            https://raw.githubusercontent.com/darlene-he/location/main/data/location.json \
            -o location-原始.json

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add location-原始.json
          git commit -m "Manual update location-原始.json" || echo "No changes"

      - name: Push changes
        run: git push
