name: "Go 查询行政区划编码“

on:
  workflow_dispatch:
    inputs:
      name:
        description: "输入名称"
        required: true
        default: "海淀区"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run
        run: go run scripts/多级查询.go "${{ github.event.inputs.name }}"
